### ISSUE TITLE
Extra Credit: Write a second class to implement EntryWayListInterface.

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabC-Team1#5]
Write a second class to implement EntryWayListInterface. Instead of using an array or linked nodes, use either an AList or LList object as your instance data variable. In this way, you are using an existing data type (AList or LList) to implement a new data type (EntryWayListInterface). Inside the methods of this class, invoke methods on the AList or LList object to accomplish the task.

**Comment by karlnicholas** [comment]
Should be interesting.

**Comment by karlnicholas** [comment]
Jill, 

"Instead of using an array or linked nodes, use either an AList or LList object **as your instance data** variable"

I think you are misunderstanding this. The assignment is to use a working LList (or AList ) class in place if the array. We were given working versions of those classes in week5's source. Let's copy one or both of those files into this repo and look at which one we want to use. Thanks,

Karl.

**Comment by jillHuang7** [comment]
Sorry for my misunderstanding. I found AList from week4, LList from week5, and updated both. Hope I were right.

**Comment by karlnicholas** [comment]
Looks good. Are you going to pick one and have a first go at it? I vote for AList because that seems to be the closest to what EntryWayListInterface needs.

**Comment by alternatebow** [comment]
Yes I would also go with a AList as well. Seems more straightforward to
manipulate and access it's contents.

**Comment by karlnicholas** [comment]
Need to declare type T

        SecondEntryWayList.java:4: error: cannot find symbol
                private AList<T> aList;
                              ^
          symbol:   class T
          location: class SecondEntryWayList
        SecondEntryWayList.java:5: error: cannot find symbol
                private AList<T> internalList;
                              ^
          symbol:   class T
          location: class SecondEntryWayList
        SecondEntryWayList.java:20: error: cannot find symbol
                public boolean insertHead(T newEntry) {
                                          ^
          symbol:   class T
          location: class SecondEntryWayList
        SecondEntryWayList.java:37: error: cannot find symbol
            public boolean insertTail(T newEntry) {
                                      ^
          symbol:   class T
          location: class SecondEntryWayList
        SecondEntryWayList.java:51: error: cannot find symbol
                public T deleteHead() {
                       ^
          symbol:   class T
          location: class SecondEntryWayList
        SecondEntryWayList.java:64: error: cannot find symbol
                public T deleteTail() {
                       ^
          symbol:   class T
          location: class SecondEntryWayList
        SecondEntryWayList.java:83: error: cannot find symbol
                public boolean contains(T anEntry) {
                                        ^
          symbol:   class T
          location: class SecondEntryWayList
        Note: Some input files use unchecked or unsafe operations.
        Note: Recompile with -Xlint:unchecked for details.
        7 errors

**Comment by alternatebow** [comment]
Is there a reason for an internal list within the SecondEntryWayList class?

**Comment by alternatebow** [comment]
Did some revision on it... having some issues with Git right now (which is
why I'm not doing a pull request myself), but look it over and see if it's
good.

**Comment by karlnicholas** [comment]
Jill, You need to do a pull first and get the latest code. I'm not sure but it looks like you are checking in errors that were already fixed. You were making your changes on a branch and then merging them, what happened to that? Also, It's really bad practice to check in code that doesn't compile and I have to ask you not to do that. While there would typically be test cases and stricter permissions on the project and source control, this project is too informal and short to worry about that. However, it is important to leave the code so that it at least compiles and be sure to pull in other's changes before adding your own. 

All in all I think the extra-credit is coming along well and I'm happy to see the progress it's making. I made some updates were I thought it made sense, and we'll have to expand the driver program to test this new class as well. We should open an issue for that.

**Comment by alternatebow** [comment]
Don't worry I made sure this complied on my end (although it did say
they're were some "unsafe actions" still not sure what that meant).

**Comment by jillHuang7** [comment]
Oh no.. I apologized for my bad operating :(
GitHub is a great platform, but really need to use it carefully ..
Thank you for teaching, catching, and fixing my mistakes.
I will try my best to get the GitHub..
Apologize again.

**Comment by karlnicholas** [comment]
Hi Calvin, the unsafe is usually generics, so intead of `new AList()`  do a `new AList<T>()`. I made changes too so you'll have to fetch and merge (I think) and inspect and resolve the differences. If you don't want to do that then push a branch and I can give it a go. 

Hi Jill, no worries, you're doing great, especially for a first time `git` user. Using source control is above and beyond the level of CS111B at this point, so bonus points to you for being here.

**Comment by alternatebow** [comment]
So I've been using Git from the terminal to access github. As of lately
I've been having issues (not linking to the right repository, not
registering pull requests, etc). But in any case, I have complied and
basically copied over the driver program for the SecondEntryWayList class.
It complies and displays the results that we want. If some one can look it
over and push it to the repo that would be super...

**Comment by karlnicholas** [comment]
I think I've gotten it merged. Have a look. I also deleted extra files so that only what is needed is now in the repo. Closing extra credit issues and moving to sign-off.
